interface IThemes {
    [key: string]: ITheme
}

export interface ITheme {
    code: string,
    description: string,
    theme: IThemeData
}

export interface IThemeData {
    "fix-profile-color"?: string;
    "fix-profile-text-color"?: string;
    "fix-profile-border-color"?: string;
    "body-color": string;
    "header-color": string;
    "logo-color": string;
    "body-text-color": string;
    "header-text-color": string;
    "border-color": string;
    "border-selected-color": string;
    "input-color": string;
    "option-disabled-color": string;
    "option-selected-color": string;
    "button-color": string;
    "button-border-color": string;
    "button-hover-color": string;
    "button-delete-color": string;
    "modal-color": string;
    "modal-button-color": string;
    "modal-border-color": string;
    "combo-color": string;
    "combo-hover-color": string;
    "combo-shadow-color": string;
    "selected-gutter": string;
    "selected-line": string;
    "string-color": string;
    "number-color": string;
    "boolean-color": string;
    "undefined-color": string;
    "tag-color": string;
    "scrollbar-track-color": string;
    "scrollbar-color": string;
    "scrollbar-hover-color": string;
    "landing-area-color": string;
}

export const isITheme = (obj: any): obj is ITheme => {
    return (
        typeof obj === 'object' &&
        obj !== null &&
        typeof obj.code === 'string' &&
        typeof obj.description === 'string' &&
        isIThemeData(obj.theme)
    );
};

export const isIThemeData = (obj: any): obj is IThemeData => {
    if (typeof obj !== 'object' || obj === null) {
        return false;
    }

    const templateKeys = Object.keys(ThemeTemplate);
    const objKeys = Object.keys(obj);

    return (
        templateKeys.length === objKeys.length &&
        templateKeys.every(key => typeof obj[key] === 'string')
    );
};

export const Themes: IThemes = {
    marine: {
        code: "marine",
        description: "Marine Go",
        theme: {
            "logo-color": "#f8f8f2",
            "body-color": "#1e2a38",
            "body-text-color": "#f8f8f2",
            "header-color": "#1e2a38",
            "header-text-color": "#f8f8f2",
            "border-color": "#4a6a7b",
            "border-selected-color": "#2980b9",
            "input-color": "#25313e",
            "option-disabled-color": "#9e9d9d",
            "option-selected-color": "#2980b9",
            "button-color": "#395870",
            "button-border-color": "#6b93ad",
            "button-hover-color": "#e0e0e0",
            "button-delete-color": "#e74c3c",
            "modal-color": "#2f3f4f",
            "modal-button-color": "#5d6d7e",
            "modal-border-color": "#3d4d5d",
            "combo-color": "#3c4c5c",
            "combo-hover-color": "#4d5d6d",
            "combo-shadow-color": "#101820",
            "selected-gutter": "#95a5a6",
            "selected-line": "#ffffff1a",
            "string-color": "#ff6b81",
            "number-color": "#1abc9c",
            "boolean-color": "#3498db",
            "undefined-color": "#9b59b6",
            "tag-color": "#2ecc71",
            "scrollbar-track-color": "#555f68",
            "scrollbar-color": "#bdc3c7",
            "scrollbar-hover-color": "#ecf0f1",
            "landing-area-color": "#ffffff"
        }
    },
    ocean: {
        code: "ocean",
        description: "Ocean PostgreSQL",
        theme: {
            "logo-color": "#f0f6f8",
            "body-color": "#0b1d26",
            "body-text-color": "#f0f6f8",
            "header-color": "#0b1d26",
            "header-text-color": "#f0f6f8",
            "border-color": "#254d5f",
            "border-selected-color": "#1f3a4c",
            "input-color": "#112630",
            "option-disabled-color": "#7b99a5",
            "option-selected-color": "#1f3a4c",
            "button-color": "#1f3a4c",
            "button-border-color": "#356678",
            "button-hover-color": "#e4f9ff",
            "button-delete-color": "#ff4f5e",
            "modal-color": "#1a2f3b",
            "modal-button-color": "#3c5c6f",
            "modal-border-color": "#2b4b5d",
            "combo-color": "#243f4f",
            "combo-hover-color": "#2e5567",
            "combo-shadow-color": "#0a1015",
            "selected-gutter": "#7aa0b4",
            "selected-line": "#ffffff1a",
            "string-color": "#ffa07a",
            "number-color": "#00ced1",
            "boolean-color": "#7ec8e3",
            "undefined-color": "#ad5edb",
            "tag-color": "#3ed39e",
            "scrollbar-track-color": "#4b6a7d",
            "scrollbar-color": "#a8c4cc",
            "scrollbar-hover-color": "#d4f0f8",
            "landing-area-color": "#eef9fb"
        }
    },
    desert: {
        code: "desert",
        description: "Desert Rust",
        theme: {
            "logo-color": "#ffe9d6",
            "body-color": "#2f1b0c",
            "body-text-color": "#ffe9d6",
            "header-color": "#2f1b0c",
            "header-text-color": "#ffe9d6",
            "border-color": "#a6623f",
            "border-selected-color": "#cc7641",
            "input-color": "#3b2616",
            "option-disabled-color": "#bfa393",
            "option-selected-color": "#cc7641",
            "button-color": "#cc7641",
            "button-border-color": "#e8945e",
            "button-hover-color": "#fff0e0",
            "button-delete-color": "#ff5c3d",
            "modal-color": "#4e2e1b",
            "modal-button-color": "#b37755",
            "modal-border-color": "#6c3e26",
            "combo-color": "#593620",
            "combo-hover-color": "#72482b",
            "combo-shadow-color": "#1a0d06",
            "selected-gutter": "#d6a178",
            "selected-line": "#ffffff1a",
            "string-color": "#ff9966",
            "number-color": "#ffc34d",
            "boolean-color": "#ffd699",
            "undefined-color": "#df8ef0",
            "tag-color": "#f5cb5c",
            "scrollbar-track-color": "#ac7d5c",
            "scrollbar-color": "#f2b899",
            "scrollbar-hover-color": "#ffe0c4",
            "landing-area-color": "#fff5ec"
        }
    },
    forest: {
        code: "forest",
        description: "Forest MongoDB",
        theme: {
            "logo-color": "#e8f5e9",
            "body-color": "#1b2d24",
            "body-text-color": "#e8f5e9",
            "header-color": "#1b2d24",
            "header-text-color": "#e8f5e9",
            "border-color": "#40654a",
            "border-selected-color": "#365e45",
            "input-color": "#243c2f",
            "option-disabled-color": "#9ebfaf",
            "option-selected-color": "#365e45",
            "button-color": "#365e45",
            "button-border-color": "#578b6c",
            "button-hover-color": "#d6fbe3",
            "button-delete-color": "#ef5350",
            "modal-color": "#2c4636",
            "modal-button-color": "#4b7d5f",
            "modal-border-color": "#395e4a",
            "combo-color": "#3a5a46",
            "combo-hover-color": "#49745a",
            "combo-shadow-color": "#121f17",
            "selected-gutter": "#91bfa1",
            "selected-line": "#ffffff1a",
            "string-color": "#a5d6a7",
            "number-color": "#26c6da",
            "boolean-color": "#81d4fa",
            "undefined-color": "#ba68c8",
            "tag-color": "#80cbc4",
            "scrollbar-track-color": "#587d6a",
            "scrollbar-color": "#aedccf",
            "scrollbar-hover-color": "#e0f2f1",
            "landing-area-color": "#f0fdf4"
        }
    },
    tropical: {
        code: "tropical",
        description: "Tropical Clojure",
        theme: {
            "logo-color": "#e1f7ff",
            "body-color": "#0d3c49",
            "body-text-color": "#e1f7ff",
            "header-color": "#0d3c49",
            "header-text-color": "#e1f7ff",
            "border-color": "#58a0b3",
            "border-selected-color": "#3a8e99",
            "input-color": "#184d57",
            "option-disabled-color": "#6a8890",
            "option-selected-color": "#3a8e99",
            "button-color": "#3a8e99",
            "button-border-color": "#5db6c6",
            "button-hover-color": "#c1f7ff",
            "button-delete-color": "#ff6666",
            "modal-color": "#1c5a67",
            "modal-button-color": "#5ca9b8",
            "modal-border-color": "#487983",
            "combo-color": "#2b4d56",
            "combo-hover-color": "#406e78",
            "combo-shadow-color": "#0a1f26",
            "selected-gutter": "#76b9c1",
            "selected-line": "#ffffff1f",
            "string-color": "#ff9b93",
            "number-color": "#16b79d",
            "boolean-color": "#f8b400",
            "undefined-color": "#ff73e5",
            "tag-color": "#66db66",
            "scrollbar-track-color": "#3a646c",
            "scrollbar-color": "#a1c8c9",
            "scrollbar-hover-color": "#c5f1f3",
            "landing-area-color": "#e0f8f9"
        }
    },
    autumn: {
        code: "autumn",
        description: "Autumn Java",
        theme: {
            "logo-color": "#f9e8c2",
            "body-color": "#2a1a0f",
            "body-text-color": "#f9e8c2",
            "header-color": "#2a1a0f",
            "header-text-color": "#f9e8c2",
            "border-color": "#6d4f4b",
            "border-selected-color": "#b34d4d",
            "input-color": "#3e2a1e",
            "option-disabled-color": "#bba392",
            "option-selected-color": "#b34d4d",
            "button-color": "#b34d4d",
            "button-border-color": "#d2897c",
            "button-hover-color": "#ffbe96",
            "button-delete-color": "#e7432a",
            "modal-color": "#3b2e26",
            "modal-button-color": "#855c4d",
            "modal-border-color": "#6a4e3b",
            "combo-color": "#54352b",
            "combo-hover-color": "#6d4e3a",
            "combo-shadow-color": "#1a1108",
            "selected-gutter": "#d1a26a",
            "selected-line": "#ffffff1f",
            "string-color": "#ff8260",
            "number-color": "#b8cc00",
            "boolean-color": "#d1a458",
            "undefined-color": "#f3e4a6",
            "tag-color": "#ff9e2d",
            "scrollbar-track-color": "#5b3c2a",
            "scrollbar-color": "#f5c6b6",
            "scrollbar-hover-color": "#f9d7bd",
            "landing-area-color": "#fcf2e7"
        }
    },
    twilight: {
        code: "twilight",
        description: "Twilight Typescript",
        theme: {
            "logo-color": "#e0e1e7",
            "body-color": "#282a36",
            "body-text-color": "#e0e1e7",
            "header-color": "#282a36",
            "header-text-color": "#e0e1e7",
            "border-color": "#44475a",
            "border-selected-color": "#546392",
            "input-color": "#37384a",
            "option-disabled-color": "#858a9b",
            "option-selected-color": "#5d6ea2",
            "button-color": "#6272a4",
            "button-border-color": "#7d8bb5",
            "button-hover-color": "#c3e8fb",
            "button-delete-color": "#ff5555",
            "modal-color": "#3b3f52",
            "modal-button-color": "#7289da",
            "modal-border-color": "#505f76",
            "combo-color": "#383d49",
            "combo-hover-color": "#4f5e6b",
            "combo-shadow-color": "#1e232e",
            "selected-gutter": "#6272a4",
            "selected-line": "#ffffff1f",
            "string-color": "#ff79c6",
            "number-color": "#bd93f9",
            "boolean-color": "#ffb86c",
            "undefined-color": "#ff6e6e",
            "tag-color": "#50fa7b",
            "scrollbar-track-color": "#4d5f72",
            "scrollbar-color": "#b9c9d2",
            "scrollbar-hover-color": "#a1bbcc",
            "landing-area-color": "#f8f9fc"
        }
    },
    sunrise: {
        code: "sunrise",
        description: "Sunrise Fortran",
        theme: {
            "logo-color": "#fff5d4",
            "body-color": "#3a1d4e",
            "body-text-color": "#fff5d4",
            "header-color": "#3a1d4e",
            "header-text-color": "#fff5d4",
            "border-color": "#6f3879",
            "border-selected-color": "#5d2a6d",
            "input-color": "#3f1b46",
            "option-disabled-color": "#bda8c2",
            "option-selected-color": "#5d2a6d",
            "button-color": "#5d2a6d",
            "button-border-color": "#9f5397",
            "button-hover-color": "#f4e0fa",
            "button-delete-color": "#e84c7e",
            "modal-color": "#4b2d66",
            "modal-button-color": "#703e7f",
            "modal-border-color": "#5c2e68",
            "combo-color": "#4e2d5b",
            "combo-hover-color": "#673a74",
            "combo-shadow-color": "#1a111a",
            "selected-gutter": "#ae7ecf",
            "selected-line": "#ffffff1f",
            "string-color": "#ff9e5d",
            "number-color": "#c9d4ff",
            "boolean-color": "#c988ff",
            "undefined-color": "#f97bf0",
            "tag-color": "#ff9e9e",
            "scrollbar-track-color": "#7e4a82",
            "scrollbar-color": "#dab3d7",
            "scrollbar-hover-color": "#efdaf4",
            "landing-area-color": "#f8e3f8"
        }
    },
    quartz: {
        code: "quartz",
        description: "Quartz Elixir",
        theme: {
            "logo-color": "#ffeaf4",
            "body-color": "#2a1a26",
            "body-text-color": "#ffeaf4",
            "header-color": "#2a1a26",
            "header-text-color": "#ffeaf4",
            "border-color": "#8c4a70",
            "border-selected-color": "#9e4774",
            "input-color": "#3b2435",
            "option-disabled-color": "#cfa4b8",
            "option-selected-color": "#b25283",
            "button-color": "#b25283",
            "button-border-color": "#d0709d",
            "button-hover-color": "#ffd4e8",
            "button-delete-color": "#ff6f91",
            "modal-color": "#4a2c3e",
            "modal-button-color": "#c96f98",
            "modal-border-color": "#7d4565",
            "combo-color": "#5c2d46",
            "combo-hover-color": "#824365",
            "combo-shadow-color": "#1c0e18",
            "selected-gutter": "#f1a7c7",
            "selected-line": "#ffffff1a",
            "string-color": "#ffa3b5",
            "number-color": "#ffbad2",
            "boolean-color": "#fcb8d2",
            "undefined-color": "#ea97de",
            "tag-color": "#ffccd5",
            "scrollbar-track-color": "#a15f7f",
            "scrollbar-color": "#f4b5ce",
            "scrollbar-hover-color": "#ffe1ef",
            "landing-area-color": "#fff1f7"
        }
    },
    dragon: {
        code: "dragon",
        description: "Dragon Pascal",
        theme: {
            "logo-color": "#fafffc",
            "body-color": "#0f0026",
            "body-text-color": "#fafffc",
            "header-color": "#240048",
            "header-text-color": "#fafffc",
            "border-color": "#ff00cc",
            "border-selected-color": "#33ccff",
            "input-color": "#1c003f",
            "option-disabled-color": "#a0529d",
            "option-selected-color": "#00ff90",
            "button-color": "#00ffe7",
            "button-border-color": "#00ff90",
            "button-hover-color": "#fafffc",
            "button-delete-color": "#ff006e",
            "modal-color": "#240048",
            "modal-button-color": "#ff6ec7",
            "modal-border-color": "#00f7ff",
            "combo-color": "#35005b",
            "combo-hover-color": "#6f00a3",
            "combo-shadow-color": "#02000a",
            "selected-gutter": "#ff85e1",
            "selected-line": "#ffffff20",
            "string-color": "#fcbf49",
            "number-color": "#00f0ff",
            "boolean-color": "#fffb00",
            "undefined-color": "#d100ff",
            "tag-color": "#39ff14",
            "scrollbar-track-color": "#330033",
            "scrollbar-color": "#ff00ff",
            "scrollbar-hover-color": "#ffccff",
            "landing-area-color": "#1a0033"
        }
    },
    vintage: {
        code: "vintage",
        description: "Vintage COBOL",
        theme: {
            "logo-color": "#3b322c",
            "body-color": "#f5f0e6",
            "body-text-color": "#3b322c",
            "header-color": "#e3d6c3",
            "header-text-color": "#3b322c",
            "border-color": "#a69888",
            "border-selected-color": "#c3a384",
            "input-color": "#e8e0d1",
            "option-disabled-color": "#b8a79a",
            "option-selected-color": "#c3a384",
            "button-color": "#c3a384",
            "button-border-color": "#9f7f65",
            "button-hover-color": "#fff8f0",
            "button-delete-color": "#b75d5d",
            "modal-color": "#e3d6c3",
            "modal-button-color": "#ac9275",
            "modal-border-color": "#bba58e",
            "combo-color": "#d3bca2",
            "combo-hover-color": "#c2a285",
            "combo-shadow-color": "#6e6254",
            "selected-gutter": "#cab79e",
            "selected-line": "#00000010",
            "string-color": "#8c5e3c",
            "number-color": "#5b7365",
            "boolean-color": "#9a7750",
            "undefined-color": "#b983a6",
            "tag-color": "#688b76",
            "scrollbar-track-color": "#d2c3af",
            "scrollbar-color": "#aa947b",
            "scrollbar-hover-color": "#eee3d3",
            "landing-area-color": "#fdfaf4"
        }
    },
    shelter: {
        code: "shelter",
        description: "Shelter Vim",
        theme: {
            "fix-profile-color": "#000000",
            "fix-profile-text-color": "#00ff00",
            "fix-profile-border-color": "#00ff00",
            "logo-color": "#00ff00",
            "body-color": "#000000",
            "body-text-color": "#00ff00",
            "header-color": "#000000",
            "header-text-color": "#00ff00",
            "border-color": "#008000",
            "border-selected-color": "#006600",
            "input-color": "#001100",
            "option-disabled-color": "#4d994d",
            "option-selected-color": "#003300",
            "button-color": "#003300",
            "button-border-color": "#00cc00",
            "button-hover-color": "#00ff66",
            "button-delete-color": "#ff0033",
            "modal-color": "#001a00",
            "modal-button-color": "#005500",
            "modal-border-color": "#007700",
            "combo-color": "#002200",
            "combo-hover-color": "#004400",
            "combo-shadow-color": "#000a00",
            "selected-gutter": "#00cc66",
            "selected-line": "#00ff0020",
            "string-color": "#33ff33",
            "number-color": "#00ffee",
            "boolean-color": "#66ffcc",
            "undefined-color": "#00ffff",
            "tag-color": "#33cc33",
            "scrollbar-track-color": "#003300",
            "scrollbar-color": "#00aa00",
            "scrollbar-hover-color": "#00ff99",
            "landing-area-color": "#001a00"
        }
    },
    nevada: {
        code: "nevada",
        description: "Nevada Emacs",
        theme: {
            "fix-profile-color": "#000000",
            "fix-profile-text-color": "#ff9900",
            "fix-profile-border-color": "#ff9900",
            "logo-color": "#ff9900",
            "body-color": "#000000",
            "body-text-color": "#ff9900",
            "header-color": "#000000",
            "header-text-color": "#ff9900",
            "border-color": "#cc6600",
            "border-selected-color": "#994c00",
            "input-color": "#331a00",
            "option-disabled-color": "#cc9966",
            "option-selected-color": "#663300",
            "button-color": "#663300",
            "button-border-color": "#ff9900",
            "button-hover-color": "#ffcc66",
            "button-delete-color": "#ff0033",
            "modal-color": "#331a00",
            "modal-button-color": "#996600",
            "modal-border-color": "#cc7700",
            "combo-color": "#4d2600",
            "combo-hover-color": "#804000",
            "combo-shadow-color": "#1a0d00",
            "selected-gutter": "#ffb84d",
            "selected-line": "#ff990020",
            "string-color": "#ffcc66",
            "number-color": "#ffddaa",
            "boolean-color": "#ffbb88",
            "undefined-color": "#ffccaa",
            "tag-color": "#ff9933",
            "scrollbar-track-color": "#663300",
            "scrollbar-color": "#ff8800",
            "scrollbar-hover-color": "#ffcc99",
            "landing-area-color": "#331a00"
        }
    },
    solarized: {
        code: "solarized",
        description: "Solarized MySQL",
        theme: {
            "logo-color": "#586e75",
            "body-color": "#fdf6e3",
            "body-text-color": "#586e75",
            "header-color": "#eee8d5",
            "header-text-color": "#586e75",
            "border-color": "#93a1a1",
            "border-selected-color": "#d4ccaa",
            "input-color": "#eee8d5",
            "option-disabled-color": "#93a1a1",
            "option-selected-color": "#e0dac2",
            "button-color": "#eee8d5",
            "button-border-color": "#93a1a1",
            "button-hover-color": "#e0dac2",
            "button-delete-color": "#dc322f",
            "modal-color": "#fdf6e3",
            "modal-button-color": "#eee8d5",
            "modal-border-color": "#93a1a1",
            "combo-color": "#eee8d5",
            "combo-hover-color": "#e0dac2",
            "combo-shadow-color": "#657b83",
            "selected-gutter": "#dcd6bd",
            "selected-line": "#657b8330",
            "string-color": "#2aa198",
            "number-color": "#d33682",
            "boolean-color": "#859900",
            "undefined-color": "#6c71c4",
            "tag-color": "#b58900",
            "scrollbar-track-color": "#eee8d5",
            "scrollbar-color": "#93a1a1",
            "scrollbar-hover-color": "#586e75",
            "landing-area-color": "#fdf6e3"
        }
    },
    nebula: {
        code: "nebula",
        description: "Nebula C++",
        theme: {
            "logo-color": "#c9d1d9",
            "body-color": "#0d1117",
            "body-text-color": "#c9d1d9",
            "header-color": "#161b22",
            "header-text-color": "#c9d1d9",
            "border-color": "#30363d",
            "border-selected-color": "#22262b",
            "input-color": "#161b22",
            "option-disabled-color": "#8b949e",
            "option-selected-color": "#383f47",
            "button-color": "#21262d",
            "button-border-color": "#30363d",
            "button-hover-color": "#30363d",
            "button-delete-color": "#f85149",
            "modal-color": "#161b22",
            "modal-button-color": "#21262d",
            "modal-border-color": "#30363d",
            "combo-color": "#21262d",
            "combo-hover-color": "#2d333b",
            "combo-shadow-color": "#0d1117",
            "selected-gutter": "#3b4048",
            "selected-line": "#58a6ff22",
            "string-color": "#a5d6ff",
            "number-color": "#79c0ff",
            "boolean-color": "#ff7b72",
            "undefined-color": "#d2a8ff",
            "tag-color": "#56d364",
            "scrollbar-track-color": "#21262d",
            "scrollbar-color": "#6e7681",
            "scrollbar-hover-color": "#8b949e",
            "landing-area-color": "#0d1117"
        }
    },
    sun: {
        code: "sun",
        description: "Sun Hadoop",
        theme: {
            "logo-color": "#4e342e",
            "body-color": "#fff8e1",
            "body-text-color": "#4e342e",
            "header-color": "#ffe0b2",
            "header-text-color": "#4e342e",
            "border-color": "#a1887f",
            "border-selected-color": "#ffb74d",
            "input-color": "#ffecb3",
            "option-disabled-color": "#bcaAA4",
            "option-selected-color": "#ffc266",
            "button-color": "#ffe0b2",
            "button-border-color": "#bcaaa4",
            "button-hover-color": "#ffcc80",
            "button-delete-color": "#e57373",
            "modal-color": "#ffecb3",
            "modal-button-color": "#ffe0b2",
            "modal-border-color": "#a1887f",
            "combo-color": "#ffe0b2",
            "combo-hover-color": "#ffcc80",
            "combo-shadow-color": "#6d4c41",
            "selected-gutter": "#d7ccc8",
            "selected-line": "#ffcc8040",
            "string-color": "#f57c00",
            "number-color": "#ff8f00",
            "boolean-color": "#6d4c41",
            "undefined-color": "#9c27b0",
            "tag-color": "#afb42b",
            "scrollbar-track-color": "#ffe0b2",
            "scrollbar-color": "#bcaaa4",
            "scrollbar-hover-color": "#a1887f",
            "landing-area-color": "#fff3e0"
        }
    },
    strawberry: {
        code: "strawberry",
        description: "Strawberry Ruby",
        theme: {
            "logo-color": "#4a4a4a",
            "body-color": "#fff0f6",
            "body-text-color": "#4a4a4a",
            "header-color": "#ffd6e0",
            "header-text-color": "#4a4a4a",
            "border-color": "#ffacc0",
            "border-selected-color": "#ff94a2",
            "input-color": "#ffe6ec",
            "option-disabled-color": "#c9c9c9",
            "option-selected-color": "#ffb3d1",
            "button-color": "#ffd6e0",
            "button-border-color": "#ffc1cc",
            "button-hover-color": "#ffe6f0",
            "button-delete-color": "#ff94a2",
            "modal-color": "#fff5f9",
            "modal-button-color": "#ffd6e0",
            "modal-border-color": "#ffc1cc",
            "combo-color": "#ffe0eb",
            "combo-hover-color": "#fff5f9",
            "combo-shadow-color": "#e8cdd3",
            "selected-gutter": "#ffc1cc",
            "selected-line": "#ff94a230",
            "string-color": "#ff80ab",
            "number-color": "#80cbc4",
            "boolean-color": "#fbc02d",
            "undefined-color": "#ba68c8",
            "tag-color": "#ffb74d",
            "scrollbar-track-color": "#ffe0eb",
            "scrollbar-color": "#e8cdd3",
            "scrollbar-hover-color": "#ffc1cc",
            "landing-area-color": "#fff5f9"
        }
    },
    cyberpunk_0: {
        code: "cyberpunk_0",
        description: "Cyberpunk PostgreSQL",
        theme: {
            "logo-color": "#fdfdfe",
            "body-color": "#0f0f1b",
            "body-text-color": "#fdfdfe",
            "header-color": "#0f0f1b",
            "header-text-color": "#fdfdfe",
            "border-color": "#00ccff",
            "border-selected-color": "#66ffff",
            "input-color": "#1e1e2e",
            "option-disabled-color": "#a6a6b6",
            "option-selected-color": "#004d99",
            "button-color": "#00334d",
            "button-border-color": "#00ccff",
            "button-hover-color": "#1ad1ff",
            "button-delete-color": "#ff0055",
            "modal-color": "#002e4d",
            "modal-button-color": "#00334d",
            "modal-border-color": "#00ccff",
            "combo-color": "#001a33",
            "combo-hover-color": "#005a8c",
            "combo-shadow-color": "#00ccff",
            "selected-gutter": "#0080ff",
            "selected-line": "#00ffff30",
            "string-color": "#00ffff",
            "number-color": "#ffcc00",
            "boolean-color": "#00baff",
            "undefined-color": "#0099cc",
            "tag-color": "#00ff00",
            "scrollbar-track-color": "#001a2a",
            "scrollbar-color": "#0080ff",
            "scrollbar-hover-color": "#00ccff",
            "landing-area-color": "#001e2a"
        }
    },
    cyberpunk_1: {
        code: "cyberpunk_1",
        description: "Cyberpunk GraphQL",
        theme: {
            "logo-color": "#fdfdfe",
            "body-color": "#0f0f1b",
            "body-text-color": "#fdfdfe",
            "header-color": "#0f0f1b",
            "header-text-color": "#fdfdfe",
            "border-color": "#ff00cc",
            "border-selected-color": "#ff66ff",
            "input-color": "#1e1e2e",
            "option-disabled-color": "#a6a6b6",
            "option-selected-color": "#4d0099",
            "button-color": "#2e004f",
            "button-border-color": "#ff00cc",
            "button-hover-color": "#ff1aff",
            "button-delete-color": "#ff0055",
            "modal-color": "#2e004d",
            "modal-button-color": "#2e004f",
            "modal-border-color": "#ff00cc",
            "combo-color": "#1a0033",
            "combo-hover-color": "#2a005a",
            "combo-shadow-color": "#ff00cc",
            "selected-gutter": "#8000ff",
            "selected-line": "#00ffff30",
            "string-color": "#00ffff",
            "number-color": "#ffcc00",
            "boolean-color": "#ff44aa",
            "undefined-color": "#cc00ff",
            "tag-color": "#00ff00",
            "scrollbar-track-color": "#1a002a",
            "scrollbar-color": "#8000ff",
            "scrollbar-hover-color": "#ff00cc",
            "landing-area-color": "#1e002a"
        }
    },
    cyberpunk_2: {
        code: "cyberpunk_2",
        description: "Cyberpunk DB2",
        theme: {
            "logo-color": "#fdfdfe",
            "body-color": "#0f0f1b",
            "body-text-color": "#fdfdfe",
            "header-color": "#0f0f1b",
            "header-text-color": "#fdfdfe",
            "border-color": "#00ff66",
            "border-selected-color": "#66ff99",
            "input-color": "#1e1e2e",
            "option-disabled-color": "#a6a6b6",
            "option-selected-color": "#006633",
            "button-color": "#004d2e",
            "button-border-color": "#00ff66",
            "button-hover-color": "#33ff99",
            "button-delete-color": "#ff0055",
            "modal-color": "#00331f",
            "modal-button-color": "#004d2e",
            "modal-border-color": "#00ff66",
            "combo-color": "#002a1a",
            "combo-hover-color": "#005a3a",
            "combo-shadow-color": "#00ff66",
            "selected-gutter": "#00ff80",
            "selected-line": "#00ff9030",
            "string-color": "#00ff99",
            "number-color": "#ccff00",
            "boolean-color": "#00ffaa",
            "undefined-color": "#66ff66",
            "tag-color": "#00ffff",
            "scrollbar-track-color": "#001a1a",
            "scrollbar-color": "#00ff80",
            "scrollbar-hover-color": "#00ff66",
            "landing-area-color": "#002a1e"
        }
    },
    cyberpunk_3: {
        code: "cyberpunk_3",
        description: "Cyberpunk MySQL",
        theme: {
            "logo-color": "#fdfdfe",
            "body-color": "#0f0f1b",
            "body-text-color": "#fdfdfe",
            "header-color": "#0f0f1b",
            "header-text-color": "#fdfdfe",
            "border-color": "#ff9900",
            "border-selected-color": "#ffcc66",
            "input-color": "#1e1e2e",
            "option-disabled-color": "#a6a6b6",
            "option-selected-color": "#994d00",
            "button-color": "#4d2e00",
            "button-border-color": "#ff9900",
            "button-hover-color": "#ffb84d",
            "button-delete-color": "#ff0055",
            "modal-color": "#4d2600",
            "modal-button-color": "#4d2e00",
            "modal-border-color": "#ff9900",
            "combo-color": "#331a00",
            "combo-hover-color": "#804d00",
            "combo-shadow-color": "#ff9900",
            "selected-gutter": "#ff8000",
            "selected-line": "#ff990030",
            "string-color": "#ffcc00",
            "number-color": "#ffaa00",
            "boolean-color": "#ff7733",
            "undefined-color": "#ff6600",
            "tag-color": "#00ffcc",
            "scrollbar-track-color": "#1a1200",
            "scrollbar-color": "#ff8000",
            "scrollbar-hover-color": "#ff9900",
            "landing-area-color": "#2a1800"
        }
    },
    cyberpunk_4: {
        code: "cyberpunk_4",
        description: "Cyberpunk HBase",
        theme: {
            "logo-color": "#fdfdfe",
            "body-color": "#0f0f1b",
            "body-text-color": "#fdfdfe",
            "header-color": "#0f0f1b",
            "header-text-color": "#fdfdfe",
            "border-color": "#ff33aa",
            "border-selected-color": "#ff99cc",
            "input-color": "#1e1e2e",
            "option-disabled-color": "#a6a6b6",
            "option-selected-color": "#99004d",
            "button-color": "#4d0033",
            "button-border-color": "#ff33aa",
            "button-hover-color": "#ff66cc",
            "button-delete-color": "#ff0055",
            "modal-color": "#33001f",
            "modal-button-color": "#4d0033",
            "modal-border-color": "#ff33aa",
            "combo-color": "#2a001a",
            "combo-hover-color": "#5a0040",
            "combo-shadow-color": "#ff33aa",
            "selected-gutter": "#ff0099",
            "selected-line": "#ff99cc30",
            "string-color": "#ff66cc",
            "number-color": "#ffcc00",
            "boolean-color": "#ff3399",
            "undefined-color": "#ff66aa",
            "tag-color": "#00ffff",
            "scrollbar-track-color": "#1a0014",
            "scrollbar-color": "#ff0099",
            "scrollbar-hover-color": "#ff33aa",
            "landing-area-color": "#2a001e"
        }
    },
    cyberpunk_5: {
        code: "cyberpunk_5",
        description: "Cyberpunk MongoDB",
        theme: {
            "logo-color": "#fdfdfe",
            "body-color": "#0f0f1b",
            "body-text-color": "#fdfdfe",
            "header-color": "#0f0f1b",
            "header-text-color": "#fdfdfe",
            "border-color": "#00ffe5",
            "border-selected-color": "#66fff5",
            "input-color": "#1e1e2e",
            "option-disabled-color": "#a6a6b6",
            "option-selected-color": "#00665c",
            "button-color": "#004d47",
            "button-border-color": "#00ffe5",
            "button-hover-color": "#33fff0",
            "button-delete-color": "#ff0055",
            "modal-color": "#00332e",
            "modal-button-color": "#004d47",
            "modal-border-color": "#00ffe5",
            "combo-color": "#001a17",
            "combo-hover-color": "#005a52",
            "combo-shadow-color": "#00ffe5",
            "selected-gutter": "#00ffd0",
            "selected-line": "#00ffe530",
            "string-color": "#00ffee",
            "number-color": "#ffee00",
            "boolean-color": "#00ffc8",
            "undefined-color": "#33ffe5",
            "tag-color": "#ccff00",
            "scrollbar-track-color": "#001a17",
            "scrollbar-color": "#00ffd0",
            "scrollbar-hover-color": "#00ffe5",
            "landing-area-color": "#002a26"
        }
    },
    cyberpunk_6: {
        code: "cyberpunk_6",
        description: "Cyberpunk Neo4j",
        theme: {
            "logo-color": "#fdfdfe",
            "body-color": "#0f0f1b",
            "body-text-color": "#fdfdfe",
            "header-color": "#0f0f1b",
            "header-text-color": "#fdfdfe",
            "border-color": "#ffff33",
            "border-selected-color": "#ffff99",
            "input-color": "#1e1e2e",
            "option-disabled-color": "#a6a6b6",
            "option-selected-color": "#999900",
            "button-color": "#4d4d00",
            "button-border-color": "#ffff33",
            "button-hover-color": "#ffff66",
            "button-delete-color": "#ff0055",
            "modal-color": "#333300",
            "modal-button-color": "#4d4d00",
            "modal-border-color": "#ffff33",
            "combo-color": "#2a2a00",
            "combo-hover-color": "#5a5a00",
            "combo-shadow-color": "#ffff33",
            "selected-gutter": "#cccc00",
            "selected-line": "#ffff3030",
            "string-color": "#ffff66",
            "number-color": "#ffcc00",
            "boolean-color": "#ffee33",
            "undefined-color": "#e6ff00",
            "tag-color": "#00ffcc",
            "scrollbar-track-color": "#1a1a00",
            "scrollbar-color": "#cccc00",
            "scrollbar-hover-color": "#ffff33",
            "landing-area-color": "#2a2a00"
        }
    },
    notebook: {
        code: "notebook",
        description: "Notebook Javascript",
        theme: {
            "logo-color": "#3b3a30",
            "body-color": "#fdf6e3",
            "body-text-color": "#3b3a30",
            "header-color": "#f8f3e2",
            "header-text-color": "#3b3a30",
            "border-color": "#c0b299",
            "border-selected-color": "#a89b7d",
            "input-color": "#fcf1dc",
            "option-disabled-color": "#b9b3a9",
            "option-selected-color": "#dbcca4",
            "button-color": "#f3eacb",
            "button-border-color": "#d8c9a3",
            "button-hover-color": "#fffbe6",
            "button-delete-color": "#d96666",
            "modal-color": "#f8f3e2",
            "modal-button-color": "#eae0c4",
            "modal-border-color": "#cbbfa1",
            "combo-color": "#f3eacb",
            "combo-hover-color": "#fefae4",
            "combo-shadow-color": "#c0b299",
            "selected-gutter": "#ddd1b7",
            "selected-line": "#00000011",
            "string-color": "#9e643c",
            "number-color": "#6c7a89",
            "boolean-color": "#b07d62",
            "undefined-color": "#bd9c87",
            "tag-color": "#6d5844",
            "scrollbar-track-color": "#f3eacb",
            "scrollbar-color": "#b7a990",
            "scrollbar-hover-color": "#a6977c",
            "landing-area-color": "#fffef7"
        }
    },
    harvest: {
        code: "harvest",
        description: "Harvest CoffeeScript",
        theme: {
            "logo-color": "#5a3e36",
            "body-color": "#f4e9dc",
            "body-text-color": "#5a3e36",
            "header-color": "#f4e9dc",
            "header-text-color": "#5a3e36",
            "border-color": "#c5a88e",
            "border-selected-color": "#e0c4a3",
            "input-color": "#fffaf5",
            "option-disabled-color": "#a3978d",
            "option-selected-color": "#d6a171",
            "button-color": "#e1b07e",
            "button-border-color": "#c58c63",
            "button-hover-color": "#ffe3c6",
            "button-delete-color": "#c45c42",
            "modal-color": "#fbeedd",
            "modal-button-color": "#eab58c",
            "modal-border-color": "#d6a171",
            "combo-color": "#f4d5b0",
            "combo-hover-color": "#fff0df",
            "combo-shadow-color": "#b38c72",
            "selected-gutter": "#e0c4a3",
            "selected-line": "#ffefe03b",
            "string-color": "#d97450",
            "number-color": "#a75f2f",
            "boolean-color": "#e8871e",
            "undefined-color": "#b37a7a",
            "tag-color": "#996633",
            "scrollbar-track-color": "#f4e4ce",
            "scrollbar-color": "#b69d86",
            "scrollbar-hover-color": "#c5aa91",
            "landing-area-color": "#fff9f0"
        }
    },
    futuristic: {
        code: "futuristic",
        description: "Futuristic Solidity",
        theme: {
            "logo-color": "#e4e4e7",
            "body-color": "#0e0e10",
            "body-text-color": "#e4e4e7",
            "header-color": "#0e0e10",
            "header-text-color": "#e4e4e7",
            "border-color": "#242429",
            "border-selected-color": "#484851",
            "input-color": "#151518",
            "option-disabled-color": "#61616b",
            "option-selected-color": "#484851",
            "button-color": "#1c1c1f",
            "button-border-color": "#2e2e32",
            "button-hover-color": "#32323a",
            "button-delete-color": "#d04848",
            "modal-color": "#18181b",
            "modal-button-color": "#2a2a2f",
            "modal-border-color": "#333338",
            "combo-color": "#1c1c1f",
            "combo-hover-color": "#2a2a2f",
            "combo-shadow-color": "#0b0b0d",
            "selected-gutter": "#35353a",
            "selected-line": "#ffffff12",
            "string-color": "#82e0aa",
            "number-color": "#59dcdc",
            "boolean-color": "#9cb3ff",
            "undefined-color": "#ce85f5",
            "tag-color": "#3adbcf",
            "scrollbar-track-color": "#1a1a1d",
            "scrollbar-color": "#3e3e44",
            "scrollbar-hover-color": "#5c5c66",
            "landing-area-color": "#0b0b0d"
        }
    },
    retro: {
        code: "retro",
        description: "Retro Node",
        theme: {
            "logo-color": "#2b3a3b",
            "body-color": "#f3f8f7",
            "body-text-color": "#2b3a3b",
            "header-color": "#e1eae9",
            "header-text-color": "#2b3a3b",
            "border-color": "#7aa7a0",
            "border-selected-color": "#74a49c",
            "input-color": "#e9f1ef",
            "option-disabled-color": "#8fa7a5",
            "option-selected-color": "#9fc6c0",
            "button-color": "#c2dedb",
            "button-border-color": "#a0c5c0",
            "button-hover-color": "#dcebea",
            "button-delete-color": "#dd6e62",
            "modal-color": "#eff6f5",
            "modal-button-color": "#bfdedb",
            "modal-border-color": "#9cc2bd",
            "combo-color": "#cfe3e0",
            "combo-hover-color": "#e2f2f0",
            "combo-shadow-color": "#7ca29e",
            "selected-gutter": "#b7d4d1",
            "selected-line": "#00000010",
            "string-color": "#c67c74",
            "number-color": "#b89a48",
            "boolean-color": "#84a24a",
            "undefined-color": "#a674ad",
            "tag-color": "#3f9a94",
            "scrollbar-track-color": "#e2efed",
            "scrollbar-color": "#95bab4",
            "scrollbar-hover-color": "#bfd9d5",
            "landing-area-color": "#ffffff"
        }
    },
    midnight: {
        code: "midnight",
        description: "Midnight Cassandra",
        theme: {
            "logo-color": "#dfe6e9",
            "body-color": "#121325",
            "body-text-color": "#dfe6e9",
            "header-color": "#1b1f3a",
            "header-text-color": "#dfe6e9",
            "border-color": "#2e3451",
            "border-selected-color": "#5671dc",
            "input-color": "#1a1d3a",
            "option-disabled-color": "#616b8d",
            "option-selected-color": "#5671dc",
            "button-color": "#24305e",
            "button-border-color": "#374785",
            "button-hover-color": "#6b88ff",
            "button-delete-color": "#ff6b81",
            "modal-color": "#1b1f3a",
            "modal-button-color": "#3e51b5",
            "modal-border-color": "#29377c",
            "combo-color": "#2e3d79",
            "combo-hover-color": "#3f5ed7",
            "combo-shadow-color": "#090c1b",
            "selected-gutter": "#6fcf97",
            "selected-line": "#ffffff12",
            "string-color": "#81ecec",
            "number-color": "#a29bfe",
            "boolean-color": "#fab1a0",
            "undefined-color": "#fd79a8",
            "tag-color": "#55efc4",
            "scrollbar-track-color": "#2b3553",
            "scrollbar-color": "#4d63a6",
            "scrollbar-hover-color": "#768fff",
            "landing-area-color": "#1a2238"
        }
    },
    carnival: {
        code: "carnival",
        description: "Carnival C#",
        theme: {
            "logo-color": "#f8f8f2",
            "body-color": "#1f0a1f",
            "body-text-color": "#f8f8f2",
            "header-color": "#1e0c27",
            "header-text-color": "#f8f8f2",
            "border-color": "#3e1f47",
            "border-selected-color": "#ad3bde",
            "input-color": "#2c0f30",
            "option-disabled-color": "#8e6a9e",
            "option-selected-color": "#591782",
            "button-color": "#3d155f",
            "button-border-color": "#592b88",
            "button-hover-color": "#b567ff",
            "button-delete-color": "#ff4267",
            "modal-color": "#2c1238",
            "modal-button-color": "#7b1fa2",
            "modal-border-color": "#5e2e7e",
            "combo-color": "#41125f",
            "combo-hover-color": "#6a1b9a",
            "combo-shadow-color": "#16001a",
            "selected-gutter": "#e040fb",
            "selected-line": "#ffffff1a",
            "string-color": "#ff80ab",
            "number-color": "#80d8ff",
            "boolean-color": "#69f0ae",
            "undefined-color": "#ea80fc",
            "tag-color": "#ffab40",
            "scrollbar-track-color": "#542b60",
            "scrollbar-color": "#c26be6",
            "scrollbar-hover-color": "#e5b9f3",
            "landing-area-color": "#21021c"
        }
    },
    inferno: {
        code: "inferno",
        description: "Inferno CouchDB",
        theme: {
            "logo-color": "#ffdddd",
            "body-color": "#120000",
            "body-text-color": "#ffdddd",
            "header-color": "#330000",
            "header-text-color": "#ffdddd",
            "border-color": "#660000",
            "border-selected-color": "#ff2e2e",
            "input-color": "#1f0000",
            "option-disabled-color": "#aa4f4f",
            "option-selected-color": "#800000",
            "button-color": "#4a0000",
            "button-border-color": "#cc0000",
            "button-hover-color": "#ff4d4d",
            "button-delete-color": "#ff2a2a",
            "modal-color": "#4d0000",
            "modal-button-color": "#b30000",
            "modal-border-color": "#cc0000",
            "combo-color": "#3b0000",
            "combo-hover-color": "#660000",
            "combo-shadow-color": "#1a0000",
            "selected-gutter": "#ff7070",
            "selected-line": "#ff2a2a2a",
            "string-color": "#ff2020",
            "number-color": "#ff5e5e",
            "boolean-color": "#ff8c8c",
            "undefined-color": "#ff3e6e",
            "tag-color": "#ff4b4b",
            "scrollbar-track-color": "#330000",
            "scrollbar-color": "#ff2e2e",
            "scrollbar-hover-color": "#ff6b6b",
            "landing-area-color": "#1a0000"
        }
    },
    ice: {
        code: "ice",
        description: "Ice PHP",
        theme: {
            "logo-color": "#0d1b2a",
            "body-color": "#ffffff",
            "body-text-color": "#0d1b2a",
            "header-color": "#f7fbff",
            "header-text-color": "#0d1b2a",
            "border-color": "#a3c9f5",
            "border-selected-color": "#42a5f5",
            "input-color": "#f0f8ff",
            "option-disabled-color": "#b0bec5",
            "option-selected-color": "#b3e5fc",
            "button-color": "#b7defa",
            "button-border-color": "#90caf9",
            "button-hover-color": "#bbdefb",
            "button-delete-color": "#ef9a9a",
            "modal-color": "#f7fbff",
            "modal-button-color": "#87c5f7",
            "modal-border-color": "#42a5f5",
            "combo-color": "#e1f5fe",
            "combo-hover-color": "#b3e5fc",
            "combo-shadow-color": "#90a4ae",
            "selected-gutter": "#e3f2fd",
            "selected-line": "#cce7ff88",
            "string-color": "#1565c0",
            "number-color": "#0288d1",
            "boolean-color": "#00acc1",
            "undefined-color": "#7986cb",
            "tag-color": "#4fc3f7",
            "scrollbar-track-color": "#e3f2fd",
            "scrollbar-color": "#90caf9",
            "scrollbar-hover-color": "#64b5f6",
            "landing-area-color": "#f0f8ff"
        }
    },
    bloom: {
        code: "bloom",
        description: "Bloom GraphQL",
        theme: {
            "logo-color": "#3d001a",
            "body-color": "#f5efe6",
            "body-text-color": "#3d001a",
            "header-color": "#f7d9d9",
            "header-text-color": "#3d001a",
            "border-color": "#e2d3c0",
            "border-selected-color": "#ffb3d2",
            "input-color": "#f9f4ed",
            "option-disabled-color": "#c8b9ae",
            "option-selected-color": "#ffc6e2",
            "button-color": "#f7d9d9",
            "button-border-color": "#ff5fa2",
            "button-hover-color": "#ffc6e2",
            "button-delete-color": "#ff3e7f",
            "modal-color": "#f3e3da",
            "modal-button-color": "#ffb3d4",
            "modal-border-color": "#ff5fa2",
            "combo-color": "#f1dbcf",
            "combo-hover-color": "#ffd0e3",
            "combo-shadow-color": "#cba8a1",
            "selected-gutter": "#ffd9eb",
            "selected-line": "#ff85c218",
            "string-color": "#ff4fa6",
            "number-color": "#ff8aa1",
            "boolean-color": "#ffbfd6",
            "undefined-color": "#e38ec2",
            "tag-color": "#f5599f",
            "scrollbar-track-color": "#e5d4c7",
            "scrollbar-color": "#ffb3d1",
            "scrollbar-hover-color": "#ffcde0",
            "landing-area-color": "#fff6f9"
        }
    },
    paprika: {
        code: "paprika",
        description: "Paprika D",
        theme: {
            "logo-color": "#5C0000",
            "body-color": "#FFF5E1",
            "body-text-color": "#5C0000",
            "header-color": "#FF9248",
            "header-text-color": "#FFFFFF",
            "border-color": "#FFA500",
            "border-selected-color": "#FFD700",
            "input-color": "#FFE5B4",
            "option-disabled-color": "#FFDAB9",
            "option-selected-color": "#FFB347",
            "button-color": "#FF775E",
            "button-border-color": "#E25822",
            "button-hover-color": "#FF4500",
            "button-delete-color": "#D7263D",
            "modal-color": "#FFF3CD",
            "modal-button-color": "#FF8C42",
            "modal-border-color": "#FFA07A",
            "combo-color": "#FFE4B5",
            "combo-hover-color": "#FFDEAD",
            "combo-shadow-color": "#F4A460",
            "selected-gutter": "#FFAD60",
            "selected-line": "#FFD580",
            "string-color": "#FF6B6B",
            "number-color": "#FFA500",
            "boolean-color": "#FFD700",
            "undefined-color": "#E57373",
            "tag-color": "#FFB347",
            "scrollbar-track-color": "#FFF5E1",
            "scrollbar-color": "#FF8C00",
            "scrollbar-hover-color": "#FF4500",
            "landing-area-color": "#FFFACD"
        }

    },
    honey: {
        code: "honey",
        description: "Honey NoCode",
        theme: {
            "logo-color": "#2b1b00",
            "body-color": "#ffffff",
            "body-text-color": "#2b1b00",
            "header-color": "#ffb84d",
            "header-text-color": "#2b1b00",
            "border-color": "#e0a800",
            "border-selected-color": "#ffa000",
            "input-color": "#fff3c0",
            "option-disabled-color": "#bba577",
            "option-selected-color": "#ffe082",
            "button-color": "#ffb84d",
            "button-border-color": "#ffb300",
            "button-hover-color": "#ffe082",
            "button-delete-color": "#ff7043",
            "modal-color": "#fffbe6",
            "modal-button-color": "#ffd54f",
            "modal-border-color": "#ffa000",
            "combo-color": "#fff3cd",
            "combo-hover-color": "#ffe57f",
            "combo-shadow-color": "#e0c080",
            "selected-gutter": "#ffe082",
            "selected-line": "#ffcc801a",
            "string-color": "#ffb74d",
            "number-color": "#ffca28",
            "boolean-color": "#ffa726",
            "undefined-color": "#f48fb1",
            "tag-color": "#ffcc80",
            "scrollbar-track-color": "#fff0c1",
            "scrollbar-color": "#ffd740",
            "scrollbar-hover-color": "#ffff8d",
            "landing-area-color": "#fffaf0"
        }
    },
}

export const ThemesDefault: IThemes = {
    light: {
        code: "light",
        description: "Light",
        theme: {
            "logo-color": "#303030",
            "body-color": "#ffffff",
            "body-text-color": "#000000",
            "header-color": "#ffffff",
            "header-text-color": "#000000",
            "border-color": "#d5d5d5",
            "border-selected-color": "#9b9b9b",
            "input-color": "transparent",
            "option-disabled-color": "#9e9d9d",
            "option-selected-color": "#e2e2e2",
            "button-color": "#f9f9f9",
            "button-hover-color": "#f9f9f9",
            "button-border-color": "#d1d1d1",
            "button-delete-color": "#e4c1c1",
            "modal-color": "#f5f5f5",
            "modal-button-color": "#f9f9f9",
            "modal-border-color": "#d1d1d1",
            "combo-color": "#efefef",
            "combo-hover-color": "#f8f8f8",
            "combo-shadow-color": "#a9a9a9",
            "selected-gutter": "#e2e2e2",
            "selected-line": "#d8d8d848",
            "string-color": "#aa1111",
            "number-color": "#116644",
            "boolean-color": "#221199",
            "undefined-color": "#770088",
            "tag-color": "#008855",
            "scrollbar-track-color": "#f0f0f0",
            "scrollbar-color": "#888888",
            "scrollbar-hover-color": "#555555",
            "landing-area-color": "#000000"
        }
    },
    dark: {
        code: "dark",
        description: "Dark",
        theme: {
            "logo-color": "#f1f1f1",
            "body-color": "#232323",
            "body-text-color": "#f1f1f1",
            "header-color": "#232323",
            "header-text-color": "#f1f1f1",
            "border-color": "#6d6d6d",
            "border-selected-color": "#919191",
            "input-color": "#2d2d2d",
            "option-disabled-color": "#d1d1d1",
            "option-selected-color": "#919191",
            "button-color": "#3d3d3d",
            "button-border-color": "#5a5a5a",
            "button-hover-color": "#d1d1d1",
            "button-delete-color": "#e23e5f",
            "modal-color": "#3b3b3b",
            "modal-button-color": "#696969",
            "modal-border-color": "#454545",
            "combo-color": "#3b3b3b",
            "combo-hover-color": "#505050",
            "combo-shadow-color": "#111111",
            "selected-gutter": "#979797",
            "selected-line": "#ffffff1f",
            "string-color": "#ca2828",
            "number-color": "#11a5aa",
            "boolean-color": "#6495ed",
            "undefined-color": "#b70ace",
            "tag-color": "#28be86",
            "scrollbar-track-color": "#707070",
            "scrollbar-color": "#aaaaaa",
            "scrollbar-hover-color": "#d4d4d4",
            "landing-area-color": "#ffffff"
        }
    },
}

export const ThemeTemplate: IThemeData = {
    "fix-profile-color": "",
    "fix-profile-text-color": "",
    "fix-profile-border-color": "",
    "logo-color": "#ffffff",
    "body-color": "#ffffff",
    "body-text-color": "#ffffff",
    "header-color": "#ffffff",
    "header-text-color": "#ffffff",
    "border-color": "#ffffff",
    "border-selected-color": "#ffffff",
    "input-color": "#ffffff",
    "option-disabled-color": "#ffffff",
    "option-selected-color": "#ffffff",
    "button-color": "#ffffff",
    "button-border-color": "#ffffff",
    "button-hover-color": "#ffffff",
    "button-delete-color": "#ffffff",
    "modal-color": "#ffffff",
    "modal-button-color": "#ffffff",
    "modal-border-color": "#ffffff",
    "combo-color": "#ffffff",
    "combo-hover-color": "#ffffff",
    "combo-shadow-color": "#ffffff",
    "selected-gutter": "#95a5a6",
    "selected-line": "#ffffff",
    "string-color": "#ffffff",
    "number-color": "#ffffff",
    "boolean-color": "#ffffff",
    "undefined-color": "#ffffff",
    "tag-color": "#ffffff",
    "scrollbar-track-color": "#ffffff",
    "scrollbar-color": "#ffffff",
    "scrollbar-hover-color": "#ffffff",
    "landing-area-color": "#ffffff"
}